[serve]
# The address to serve on.
address = "0.0.0.0"
# The port to serve on.
port = 7070
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false
